#!/bin/bash
error() {
	echo;echo
	echo "*****  Error in $1  *****"
	cd $dir
	logdir="$RUN_PREFIX/install_$(date | sed -e 's/  /_/g' -e 's/ /_/g')-faillogs"
	mv $logs "$logdir"
	echo "Logs can be found in '$logdir'"
	cd ..
	exit 1
}
check_state() {
	if [ -d "$RUN_PREFIX/install" ] || [ -f "$INSTALL_PREFIX/bin/construct" ]
	then
		echo "DETECTED"
		if [ -d "$RUN_PREFIX/install/src" ]
		then
			echo "    Uninstalling current version..."
			cdir=`pwd`
			cd "$RUN_PREFIX/install/src"
			make uninstall > $logs/uninstall.log 2>&1 || error "uninstalling the old copy"
			cd ..
			rm -fr src
		else
			echo "    Source files not found."
			read -p "        Source directory: " src
			if [ -d "$src" ]
			then
				cd "$src"
				make uninstall > $logs/uninstall.log 2>&1 || error "uninstalling the old copy"
			else
				echo 'Directory not found!'
				exit 1
			fi
		fi
	else
		echo "NOT FOUND"
		mkdir -p "$RUN_PREFIX/install"
	fi
}
waitforproc() {
	i=1
	sp="o"
	while [ -h /proc/$1/exe ]
	do
		printf "\b$sp"
		case "$i" in
			"0") sp=".";i=1;;
			"1") sp="o";i=2;;
			"2") sp="0";i=3;;
			"3") sp="o";i=0;;
			*)   sp=".";i=0;;
		esac
		sleep 0.5
	done
	printf "\b. DONE\n"
}
