#!/bin/bash
DOWNLOADER="curl"
DOWNLOADER_ARGS="-L -\#"
BASEURL="https://raw.githubusercontent.com/Valinwolf/fabricator/master/"
VERSION="Fabricator "
getnettool() {
	if hash curl 2>&1 >/dev/null
	then
		return 0
	elif hash wget 2>&1 >/dev/null
	then
		DOWNLOADER="wget"
		DOWNLOADER_ARGS="-q --show-progress -O-"
		return 0
	else
		echo "No viable download programs. Please install cURL or WGet."
		exit 1
	fi
}
download() {
	if [ -f "$2" ]
	then
		read -p "This will overwrite '$2'. Do you want to proceed? [Yn] " ans
		if [ "$2" == "n" ]
		then
			return 1
		fi
	fi
	$DOWNLOADER $DOWNLOADER_ARGS "${BASEURL}${1}" > "${2}"
}
getversion() {
	VERSION="$VERSION`$DOWNLOADER $DOWNLOADER_ARGS "${BASEURL}/version"`"
}
getnettool
getversion

echo "Installing $VERSION"
mkdir -p /usr/local/{lib,etc,sbin}

echo "DOWNLOAD: Control Script (fabricator)"
download fabricator /usr/local/sbin/fabricator

echo "DOWNLOAD: Update Script (fabricate)"
download fabricate /usr/local/sbin/fabricate

echo "DOWNLOAD: Example Config"
download variables /usr/local/etc/fabricator

echo "DOWNLOAD: Function Library (fabfunct)"
download fabfunct /usr/local/lib/fabfunct

echo "CREATE: Version File"
echo "${VERSION}" > /usr/local/share/fabricator-version

echo "MOVE: Installer"
download install /usr/local/sbin/update-fabricator

echo "PERMISSIONS: Scripts"
chmod u+x /usr/local/sbin/fabricat{e,or}

echo "INSTALLATION COMPLETE"
echo "To run this script again, use '/usr/local/sbin/update-fabricator'"
